/* Auto-generated by AuthSystem - PLACEHOLDER_TIMESTAMP */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

/**
 * IMPORTANT: This file is auto-generated during deployment
 * Do not edit manually - changes will be overwritten
 *
 * When deploying to "Environments", this file is created with:
 * - apiBaseUrl: '/api' (Netlify Functions via redirect)
 * - appId: The application ID from the deployment
 * - apiKey: The production API key for the application
 *
 * Example structure:
 * {
 *   apiBaseUrl: '/api',
 *   appId: 'app_8cc6bda9-120',
 *   apiKey: 'ak_production_1754374f313c43af58875eece483a1e2'
 * }
 */

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'PLACEHOLDER_APP_ID', // Will be replaced during deployment
  apiKey: 'PLACEHOLDER_API_KEY' // Will be replaced during deployment
};
