// Helper to prepare a standalone React app for Netlify deployment
// This uses the actual PublicAuthForms component instead of static HTML

import { PUBLIC_AUTH_FORMS_TEMPLATE } from './publicAuthFormsTemplate';
import { BRANDED_PUBLIC_AUTH_TEMPLATE } from './brandedPublicAuthTemplate';
import { BRANDED_COMPONENTS_TEMPLATE } from './brandedComponentsTemplate';
import { THEME_PRESETS_TEMPLATE } from './themePresetsTemplate';
import { REGISTER_TENANT_FORM_TEMPLATE } from './registerTenantFormTemplate';
import { RESET_PASSWORD_FORM_TEMPLATE } from './resetPasswordFormTemplate';
import { VERIFY_EMAIL_FORM_TEMPLATE } from './verifyEmailFormTemplate';
import { ACCEPT_INVITATION_FORM_TEMPLATE } from './acceptInvitationFormTemplate';

export async function getReactProjectFiles(
  applicationId: string,
  apiKey: string,
  branding?: any
): Promise<Record<string, string>> {
  const files: Record<string, string> = {};

  // Generate a deployment timestamp comment to ensure files are updated
  const deployTimestamp = `/* Auto-generated by AuthSystem - ${new Date().toISOString()} */\n`;

  // package.json for the standalone app
  files['package.json'] = JSON.stringify({
    "name": "authsystem-public-forms",
    "version": "1.0.0",
    "private": true,
    "type": "module",
    "scripts": {
      "dev": "vite",
      "build": "vite build",
      "preview": "vite preview"
    },
    "dependencies": {
      "@supabase/supabase-js": "^2.57.4",
      "react": "^18.3.1",
      "react-dom": "^18.3.1",
      "react-router-dom": "^7.9.3",
      "lucide-react": "^0.344.0"
    },
    "devDependencies": {
      "@vitejs/plugin-react": "^4.3.1",
      "@types/react": "^18.3.5",
      "@types/react-dom": "^18.3.0",
      "vite": "^5.4.2",
      "typescript": "^5.5.3",
      "autoprefixer": "^10.4.18",
      "postcss": "^8.4.35",
      "tailwindcss": "^3.4.1"
    }
  }, null, 2);

  // vite.config.ts
  files['vite.config.ts'] = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: 'dist',
    emptyOutDir: true
  }
});
`;

  // tailwind.config.js
  files['tailwind.config.js'] = `export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;

  // postcss.config.js
  files['postcss.config.js'] = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

  // tsconfig.json for TypeScript configuration
  files['tsconfig.json'] = JSON.stringify({
    "compilerOptions": {
      "target": "ES2020",
      "useDefineForClassFields": true,
      "lib": ["ES2020", "DOM", "DOM.Iterable"],
      "module": "ESNext",
      "skipLibCheck": true,
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "react-jsx",
      "strict": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true
    },
    "include": ["src"],
    "references": [{ "path": "./tsconfig.node.json" }]
  }, null, 2);

  // tsconfig.node.json for Vite configuration
  files['tsconfig.node.json'] = JSON.stringify({
    "compilerOptions": {
      "composite": true,
      "skipLibCheck": true,
      "module": "ESNext",
      "moduleResolution": "bundler",
      "allowSyntheticDefaultImports": true
    },
    "include": ["vite.config.ts"]
  }, null, 2);

  // .env.example - Template for local development (optional)
  files['.env.example'] = `# These values are already embedded in the config file
# This file is only for reference
VITE_APP_ID=your-app-id
VITE_API_KEY=your-api-key
`;

  // index.html
  files['index.html'] = `<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/images/icon.svg" />
    <link rel="shortcut icon" type="image/svg+xml" href="/images/icon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AuthSystem - Autenticación</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

  // src/main.tsx
  files['src/main.tsx'] = `${deployTimestamp}import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import { envConfigService } from './services/envConfigService';

async function bootstrap() {
  try {
    await envConfigService.loadConfig();
  } catch (error) {
    console.warn('No se pudo cargar /get-env. Continuamos con fallback público.', error);
  }

  const { default: App } = await import('./App');

  ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </React.StrictMode>
  );
}

bootstrap();
`;

  // src/index.css
  files['src/index.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

  // src/App.tsx - Router for public forms using PublicAuthRouter
  files['src/App.tsx'] = `${deployTimestamp}import React from 'react';
import { Routes, Route, Navigate, useSearchParams, useLocation } from 'react-router-dom';
import { config } from './lib/config';
import PublicAuthRouter from './components/auth/PublicAuthRouter';
import CallbackHandler from './components/auth/CallbackHandler';
import RegisterTenantForm from './components/auth/RegisterTenantForm';
import ResetPasswordForm from './components/auth/ResetPasswordForm';
import VerifyEmailForm from './components/auth/VerifyEmailForm';
import AcceptInvitationForm from './components/auth/AcceptInvitationForm';

function PreserveSearchLoginRedirect() {
  const location = useLocation();
  const target = '/login' + (location.search || '');
  return <Navigate to={target} replace />;
}

export default function App() {
  const [searchParams] = useSearchParams();
  const location = useLocation();

  const appId = searchParams.get('app_id') || config.appId || '';

  // Map path to form type
  const getFormType = (): 'login' | 'register' | 'reset-password' => {
    if (location.pathname.includes('register')) return 'register';
    if (location.pathname.includes('reset')) return 'reset-password';
    return 'login';
  };

  if (!appId && !location.pathname.includes('register-tenant') && !location.pathname.includes('reset-password') && !location.pathname.includes('reset-password-confirm') && !location.pathname.includes('verify-email') && !location.pathname.includes('accept-invitation')) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="bg-white p-8 rounded-lg shadow-lg max-w-md">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Error de Configuración</h1>
          <p className="text-gray-600 mb-4">
            El parámetro <code className="bg-gray-100 px-2 py-1 rounded">app_id</code> es requerido en la URL.
          </p>
          <p className="text-sm text-gray-500">
            Ejemplo: <code className="bg-gray-100 px-2 py-1 rounded text-xs">
              /login?app_id=xxx
            </code>
          </p>
        </div>
      </div>
    );
  }

  return (
    <Routes>
      <Route
        path="/login"
        element={
          <PublicAuthRouter
            appId={appId}
            formType="login"
          />
        }
      />
      <Route
        path="/register"
        element={
          <PublicAuthRouter
            appId={appId}
            formType="register"
          />
        }
      />
      <Route path="/callback" element={<CallbackHandler />} />
      <Route path="/auth/callback" element={<CallbackHandler />} />
      <Route path="/reset-password" element={<ResetPasswordForm />} />
      <Route path="/reset-password-confirm" element={<ResetPasswordForm />} />
      <Route path="/register-tenant" element={<RegisterTenantForm />} />
      <Route path="/verify-email" element={<VerifyEmailForm />} />
      <Route path="/accept-invitation" element={<AcceptInvitationForm />} />
      <Route path="/" element={<PreserveSearchLoginRedirect />} />
      <Route path="*" element={<PreserveSearchLoginRedirect />} />
    </Routes>
  );
}
`;

  files['src/components/auth/CallbackHandler.tsx'] = `${deployTimestamp}import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle, AlertCircle, Shield, ArrowRight } from 'lucide-react';
import { requireSupabaseAnonKey, requireSupabaseUrl } from '../../lib/supabaseRuntime';

const CALLBACK_PROCESSING_PREFIX = 'auth_callback_processing';
const CALLBACK_PROCESSED_PREFIX = 'auth_callback_processed';

function buildCallbackStorageKey(prefix: string, applicationId: string, code: string) {
  return prefix + ':' + (applicationId || 'unknown') + ':' + code;
}

function decodeBase64Url(value: string) {
  const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
  const padded = normalized + '='.repeat((4 - (normalized.length % 4)) % 4);
  return atob(padded);
}

function decodeJwtClaims(token: string) {
  const tokenParts = token.split('.');
  if (tokenParts.length !== 3) {
    throw new Error('Formato de token inválido');
  }

  return JSON.parse(decodeBase64Url(tokenParts[1]));
}

export default function CallbackHandler() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [status, setStatus] = useState<'loading' | 'success' | 'error'>('loading');
  const [message, setMessage] = useState('Procesando autenticación...');
  useEffect(() => {
    const run = async () => {
      try {
        const code = searchParams.get('code');
        const applicationId = searchParams.get('application_id') || searchParams.get('app_id') || '';
        const supabaseUrl = requireSupabaseUrl();
        const supabaseAnonKey = requireSupabaseAnonKey();

        if (!code) {
          throw new Error('No se encontró un código de autenticación válido en la URL');
        }

        if (!supabaseUrl || !supabaseAnonKey) {
          throw new Error('Supabase no está configurado');
        }

        window.history.replaceState({}, document.title, window.location.pathname);

        const storageApplicationId = applicationId || 'unknown';
        const processingKey = buildCallbackStorageKey(CALLBACK_PROCESSING_PREFIX, storageApplicationId, code);
        const processedKey = buildCallbackStorageKey(CALLBACK_PROCESSED_PREFIX, storageApplicationId, code);

        if (sessionStorage.getItem(processedKey) === '1') {
          setStatus('success');
          setMessage('Esta autenticaciÃ³n ya fue procesada. Redirigiendo...');
          setTimeout(() => {
            navigate('/login', { replace: true });
          }, 1200);
          return;
        }

        if (sessionStorage.getItem(processingKey) === '1') {
          setStatus('loading');
          setMessage('Procesando autenticaciÃ³n...');
          return;
        }

        sessionStorage.setItem(processingKey, '1');

        const response = await fetch(supabaseUrl + '/functions/v1/auth-exchange-code', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + supabaseAnonKey,
            'apikey': supabaseAnonKey
          },
          body: JSON.stringify(applicationId ? { code, application_id: applicationId } : { code })
        });

        const result = await response.json();
        if (!response.ok || !result.success) {
          throw new Error(result?.error?.message || 'No se pudo completar el intercambio de código');
        }

        const data = result.data || {};
        sessionStorage.setItem('auth_token', data.access_token || '');
        sessionStorage.setItem('refresh_token', data.refresh_token || '');
        const claims = decodeJwtClaims(String(data.access_token || ''));
        sessionStorage.setItem('user_data', JSON.stringify({
          id: claims.sub || '',
          email: claims.email || '',
          name: claims.name || '',
          role: claims.role || 'user',
          roles: Array.isArray(claims.roles) ? claims.roles : (claims.role ? [claims.role] : ['user']),
          permissions: claims.permissions || {},
          permissions_hierarchy: claims.permissions_hierarchy || {},
          metadata: claims.user_metadata || {},
          tenant: claims.tenant || null,
          subscription: claims.subscription || null,
          license: claims.license || null,
          has_access: claims.has_access,
          available_plans: claims.available_plans || [],
        }));
        sessionStorage.setItem('application_data', JSON.stringify({
          id: claims.app_id || applicationId || '',
          name: claims.app_name || '',
          domain: claims.app_domain || '',
          environment: claims.environment || null,
        }));

        sessionStorage.setItem(processedKey, '1');
        sessionStorage.removeItem(processingKey);

        setStatus('success');
        setMessage('Autenticación exitosa. Redirigiendo...');

        setTimeout(() => {
          navigate('/login', { replace: true });
        }, 1500);
      } catch (error: any) {
        const code = searchParams.get('code');
        const applicationId = searchParams.get('application_id') || searchParams.get('app_id');
        if (code && applicationId) {
          const processingKey = buildCallbackStorageKey(CALLBACK_PROCESSING_PREFIX, applicationId || 'unknown', code);
          sessionStorage.removeItem(processingKey);
        }

        setStatus('error');
        setMessage(error.message || 'Error procesando la autenticación');
      }
    };

    run();
  }, [navigate, searchParams]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-xl border border-gray-200 p-8 max-w-md w-full text-center">
        {status === 'loading' && (
          <>
            <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Procesando autenticación...</h2>
            <p className="text-gray-600">Por favor espera mientras validamos tu sesión</p>
          </>
        )}

        {status === 'success' && (
          <>
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-8 h-8 text-green-500" />
            </div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">¡Autenticación Exitosa!</h2>
            <p className="text-gray-600 mb-4">{message}</p>
            <div className="mt-6 flex items-center justify-center space-x-2 text-sm text-gray-500">
              <Shield className="w-4 h-4" />
              <span>Sesión segura establecida</span>
            </div>
          </>
        )}

        {status === 'error' && (
          <>
            <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <AlertCircle className="w-8 h-8 text-red-500" />
            </div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Error de Autenticación</h2>
            <p className="text-gray-600 mb-6">{message}</p>

            <button
              onClick={() => navigate('/login', { replace: true })}
              className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg flex items-center space-x-2 mx-auto transition-colors"
            >
              <span>Intentar de nuevo</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </>
        )}
      </div>
    </div>
  );
}`;

  // src/components/auth/PublicAuthRouter.tsx - Component that loads branding from DB
  files['src/components/auth/PublicAuthRouter.tsx'] = `${deployTimestamp}import React, { useEffect, useState } from 'react';
import BrandedPublicAuth from './BrandedPublicAuth';
import { applicationService } from '../../services/applicationService';
import { supabase } from '../../lib/supabase';
import { requireSupabaseAnonKey, requireSupabaseUrl } from '../../lib/supabaseRuntime';
import { useSearchParams } from 'react-router-dom';

interface PublicAuthRouterProps {
  appId: string;
  formType: string;
}

export default function PublicAuthRouter({ appId, formType }: PublicAuthRouterProps) {
  const [appData, setAppData] = useState<any>(null);
  const [apiKey, setApiKey] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchParams] = useSearchParams();

  const validFormType = ['login', 'register', 'reset-password'].includes(formType)
    ? formType as 'login' | 'register' | 'reset-password'
    : 'login';

  useEffect(() => {
    const loadApplicationData = async () => {
      try {
        setLoading(true);
        console.log('Loading application data for:', appId);

        // Get API key from URL first
        const apiKeyFromUrl = searchParams.get('api_key');
        if (apiKeyFromUrl) {
          console.log('✅ API key from URL:', apiKeyFromUrl.substring(0, 20) + '...');
          setApiKey(apiKeyFromUrl);
        } else {
          console.warn('⚠️ No API key in URL');
        }

        try {
          const { data: app, error: appError } = await supabase
            .from('applications')
            .select('*')
            .eq('application_id', appId)
            .single();

          if (appError || !app) {
            console.error('Application not found:', appId, appError);
            setError('Application not found');
            return;
          }

          try {
            const branding = await applicationService.getBranding(app.id);
            setAppData({
              ...app,
              branding: branding || {}
            });
          } catch (brandingError) {
            console.warn('Could not load branding, using defaults:', brandingError);
            setAppData({
              ...app,
              branding: {}
            });
          }

          console.log('Application loaded:', app);

        } catch (supabaseError) {
          console.error('Supabase connection error:', supabaseError);
          setError('Failed to connect to database');
        }

      } catch (error) {
        console.error('Error loading application:', error);
        setError('Failed to load application');
      } finally {
        setLoading(false);
      }
    };

    loadApplicationData();
  }, [appId, searchParams]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Error</h1>
          <p className="text-gray-600">{error}</p>
        </div>
      </div>
    );
  }

  const decodeBase64Url = (value: string) => {
    const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
    const padded = normalized + '='.repeat((4 - (normalized.length % 4)) % 4);
    return atob(padded);
  };

  const decodeJwtClaims = (token: string) => {
    const tokenParts = String(token || '').split('.');
    if (tokenParts.length !== 3) {
      throw new Error('Formato de token invÃ¡lido');
    }

    return JSON.parse(decodeBase64Url(tokenParts[1]));
  };

  const storeAuthSessionFromTokens = (tokenData: any) => {
    if (!tokenData?.access_token) return null;

    const claims = decodeJwtClaims(tokenData.access_token);
    const roles = Array.isArray(claims.roles)
      ? claims.roles
      : claims.role
        ? [claims.role]
        : ['user'];

    sessionStorage.setItem('auth_token', tokenData.access_token);
    sessionStorage.setItem('refresh_token', tokenData.refresh_token || '');
    sessionStorage.setItem('user_data', JSON.stringify({
      id: claims.sub || '',
      email: claims.email || '',
      name: claims.name || '',
      role: claims.role || roles[0] || 'user',
      roles,
      permissions: claims.permissions || {},
      permissions_hierarchy: claims.permissions_hierarchy || {},
      metadata: claims.user_metadata || {},
      created_at: claims.user_created_at || null,
      tenant_id: claims.tenant_id || null,
      tenant_name: claims.tenant_name || null,
      tenant: claims.tenant || null,
      subscription: claims.subscription || null,
      license: claims.license || null,
      has_access: claims.has_access,
      available_plans: claims.available_plans || null,
      environment: claims.environment || null,
      last_login: new Date().toISOString()
    }));
    sessionStorage.setItem('application_data', JSON.stringify({
      id: claims.app_id || appId,
      name: claims.app_name || '',
      domain: claims.app_domain || '',
      environment: claims.environment || null
    }));

    if (typeof claims.exp === 'number') {
      sessionStorage.setItem('token_expires_at', new Date(claims.exp * 1000).toISOString());
    }

    return claims;
  };

  const handleAuthSubmit = async (formData: any) => {
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const callbackUrl = urlParams.get('callback_url') || urlParams.get('redirect_uri');

      // Get client IP
      const ipResponse = await fetch('https://api.ipify.org?format=json');
      const ipData = await ipResponse.json();
      const clientIp = ipData.ip;

      const supabaseUrl = requireSupabaseUrl();
      const supabaseAnonKey = requireSupabaseAnonKey();
      const apiBaseUrl = \`\${supabaseUrl}/functions/v1\`;

      console.log('🔧 Configuration:', {
        supabaseUrl,
        apiBaseUrl,
        applicationId: appId,
        apiKey: apiKey?.substring(0, 20) + '...',
        callbackUrl
      });

      let endpoint = '';
      let payload: any = {};

      switch (validFormType) {
        case 'login':
          endpoint = \`\${apiBaseUrl}/auth-login\`;
          payload = {
            email: formData.email,
            password: formData.password,
            application_id: appId,
            api_key: apiKey,
            callback_url: callbackUrl,
            client_ip: clientIp
          };
          break;
        case 'register':
          if (formData.password !== formData.confirmPassword) {
            throw new Error('Las contraseñas no coinciden');
          }
          endpoint = \`\${apiBaseUrl}/auth-register\`;
          payload = {
            email: formData.email,
            password: formData.password,
            name: formData.name,
            application_id: appId,
            api_key: apiKey,
            callback_url: callbackUrl,
            role: formData.role || undefined,
            client_ip: clientIp
          };
          break;
        case 'reset-password':
          endpoint = \`\${apiBaseUrl}/auth-reset-password\`;
          payload = {
            email: formData.email,
            application_id: appId,
            api_key: apiKey,
            redirect_uri: callbackUrl,
            client_ip: clientIp
          };
          break;
      }

      console.log('🚀 Making API request:', {
        endpoint,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + supabaseAnonKey.substring(0, 30) + '...',
          'apikey': supabaseAnonKey.substring(0, 30) + '...',
          'X-Client-Info': 'authsystem-public-form/1.0'
        },
        payload: { ...payload, password: '***' }
      });

      // Make API request to Supabase Edge Functions
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': \`Bearer \${supabaseAnonKey}\`,
          'apikey': supabaseAnonKey,
          'X-Client-Info': 'authsystem-public-form/1.0'
        },
        body: JSON.stringify(payload)
      });

      console.log('📡 Response received:', {
        status: response.status,
        statusText: response.statusText,
        ok: response.ok
      });

      const result = await response.json();

      const completeSuccessfulLogin = async (loginData: any) => {
        if (loginData?.callback_url) {
          console.log('🔄 Redirecting to:', loginData.callback_url);
          setTimeout(() => {
            window.location.href = loginData.callback_url;
          }, 1500);
          return;
        }

        if (loginData?.access_token) {
          storeAuthSessionFromTokens(loginData);
        }
      };

      if (!result.success) {
        if (validFormType === 'login' && result.error?.code === 'MFA_REQUIRED') {
          const challengeError: any = new Error(result.error?.message || 'MFA_REQUIRED');
          challengeError.code = 'MFA_REQUIRED';
          challengeError.data = result.data || null;
          throw challengeError;
        }

        if (validFormType === 'login' && result.error?.code === 'MFA_SETUP_REQUIRED') {
          const setupError: any = new Error(result.error?.message || 'MFA_SETUP_REQUIRED');
          setupError.code = 'MFA_SETUP_REQUIRED';
          setupError.data = result.data || null;
          throw setupError;
        }

        if (validFormType === 'login' && result.error?.code === 'MFA_SETUP_ERROR') {
          const setupError: any = new Error(result.error?.message || 'MFA_SETUP_ERROR');
          setupError.code = 'MFA_SETUP_ERROR';
          setupError.data = result.data || null;
          throw setupError;
        }

        throw new Error(result.error?.message || 'Error de autenticación');
      }

      if (validFormType === 'login') {
        await completeSuccessfulLogin(result.data);
      }

      return result.data;
    } catch (error: any) {
      console.error('❌ Auth error:', error);
      throw error;
    }
  };

  return (
    <BrandedPublicAuth
      applicationId={appId}
      formType={validFormType}
      branding={appData?.branding}
      onSubmit={handleAuthSubmit}
      onSuccess={(data) => console.log('Auth success:', data)}
      onError={(error) => console.error('Auth error:', error)}
    />
  );
}
`;

  // src/components/auth/PublicAuthForms.tsx - DEPRECATED, keeping for compatibility
  files['src/components/auth/PublicAuthForms.tsx'] = deployTimestamp + PUBLIC_AUTH_FORMS_TEMPLATE;

  // src/components/auth/BrandedPublicAuth.tsx - Main auth component with branding
  files['src/components/auth/BrandedPublicAuth.tsx'] = deployTimestamp + BRANDED_PUBLIC_AUTH_TEMPLATE;

  // src/components/auth/RegisterTenantForm.tsx - Tenant registration form
  files['src/components/auth/RegisterTenantForm.tsx'] = deployTimestamp + REGISTER_TENANT_FORM_TEMPLATE;

  // src/components/auth/ResetPasswordForm.tsx - Password reset form
  files['src/components/auth/ResetPasswordForm.tsx'] = deployTimestamp + RESET_PASSWORD_FORM_TEMPLATE;

  // src/components/auth/VerifyEmailForm.tsx - Email verification page
  files['src/components/auth/VerifyEmailForm.tsx'] = deployTimestamp + VERIFY_EMAIL_FORM_TEMPLATE;

  // src/components/auth/AcceptInvitationForm.tsx - Tenant invitation acceptance page
  files['src/components/auth/AcceptInvitationForm.tsx'] = deployTimestamp + ACCEPT_INVITATION_FORM_TEMPLATE;

  // src/components/ui/BrandedComponents.tsx - UI components with neumorphic/glass effects
  files['src/components/ui/BrandedComponents.tsx'] = deployTimestamp + BRANDED_COMPONENTS_TEMPLATE;

  // src/utils/themePresets.ts - Default branding configuration
  files['src/utils/themePresets.ts'] = deployTimestamp + THEME_PRESETS_TEMPLATE;

  // src/utils/securityValidation.ts - Security validation utilities
  files['src/utils/securityValidation.ts'] = `${deployTimestamp}/**
 * Security Validation and Sanitization Utilities
 * Protects against XSS, SQL Injection, and other attacks
 */

// Email validation - RFC 5322 compliant
const EMAIL_REGEX = /^[a-zA-Z0-9.!#$%&'*+/=?^_\\\`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

// Password strength requirements
export interface PasswordValidation {
  valid: boolean;
  errors: string[];
  strength: 'weak' | 'medium' | 'strong' | 'very-strong';
}

/**
 * Validates email format
 */
export function validateEmail(email: string): { valid: boolean; error?: string } {
  if (!email || typeof email !== 'string') {
    return { valid: false, error: 'Email es requerido' };
  }

  const trimmed = email.trim();

  if (trimmed.length === 0) {
    return { valid: false, error: 'Email no puede estar vacío' };
  }

  if (trimmed.length > 254) {
    return { valid: false, error: 'Email demasiado largo' };
  }

  if (!EMAIL_REGEX.test(trimmed)) {
    return { valid: false, error: 'Formato de email inválido' };
  }

  return { valid: true };
}

/**
 * Validates password strength
 */
export function validatePassword(password: string): PasswordValidation {
  const errors: string[] = [];
  let strength: PasswordValidation['strength'] = 'weak';

  if (!password || typeof password !== 'string') {
    return {
      valid: false,
      errors: ['Contraseña es requerida'],
      strength: 'weak'
    };
  }

  // Minimum length
  if (password.length < 8) {
    errors.push('Mínimo 8 caracteres');
  }

  // Maximum length (prevent DoS)
  if (password.length > 128) {
    errors.push('Máximo 128 caracteres');
  }

  // At least one uppercase letter
  if (!/[A-Z]/.test(password)) {
    errors.push('Al menos una letra mayúscula');
  }

  // At least one lowercase letter
  if (!/[a-z]/.test(password)) {
    errors.push('Al menos una letra minúscula');
  }

  // At least one number
  if (!/[0-9]/.test(password)) {
    errors.push('Al menos un número');
  }

  // At least one special character
  if (!/[!@#$%^&*()_+\\-=\\[\\]{};':"\\\\|,.<>\\/?]/.test(password)) {
    errors.push('Al menos un carácter especial (!@#$%^&*...)');
  }

  // Calculate strength
  let strengthScore = 0;
  if (password.length >= 8) strengthScore++;
  if (password.length >= 12) strengthScore++;
  if (/[A-Z]/.test(password)) strengthScore++;
  if (/[a-z]/.test(password)) strengthScore++;
  if (/[0-9]/.test(password)) strengthScore++;
  if (/[!@#$%^&*()_+\\-=\\[\\]{};':"\\\\|,.<>\\/?]/.test(password)) strengthScore++;
  if (password.length >= 16) strengthScore++;

  if (strengthScore <= 3) strength = 'weak';
  else if (strengthScore <= 5) strength = 'medium';
  else if (strengthScore <= 6) strength = 'strong';
  else strength = 'very-strong';

  return {
    valid: errors.length === 0,
    errors,
    strength
  };
}

/**
 * Sanitizes string input to prevent XSS
 */
export function sanitizeInput(input: string, maxLength: number = 255): string {
  if (!input || typeof input !== 'string') {
    return '';
  }

  return input
    .trim()
    // Remove dangerous characters
    .replace(/[<>'"]/g, '')
    // Remove null bytes
    .replace(/\\0/g, '')
    // Limit length
    .substring(0, maxLength);
}

/**
 * Sanitizes name (allows letters, spaces, hyphens, apostrophes)
 */
export function sanitizeName(name: string): string {
  if (!name || typeof name !== 'string') {
    return '';
  }

  return name
    .trim()
    // Only allow letters, spaces, hyphens, apostrophes
    .replace(/[^a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-']/g, '')
    // Remove multiple spaces
    .replace(/\\s+/g, ' ')
    .substring(0, 100);
}

/**
 * Validates and sanitizes all auth form data
 */
export interface AuthFormData {
  email?: string;
  password?: string;
  confirmPassword?: string;
  name?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: { [key: string]: string };
  sanitized: AuthFormData;
}

export function validateAuthForm(
  data: AuthFormData,
  formType: 'login' | 'register' | 'reset-password'
): ValidationResult {
  const errors: { [key: string]: string } = {};
  const sanitized: AuthFormData = {};

  // Email validation (required for all forms)
  if (data.email) {
    const emailValidation = validateEmail(data.email);
    if (!emailValidation.valid) {
      errors.email = emailValidation.error || 'Email inválido';
    } else {
      sanitized.email = sanitizeInput(data.email.toLowerCase(), 254);
    }
  } else {
    errors.email = 'Email es requerido';
  }

  // Password validation (required for login and register)
  if (formType !== 'reset-password') {
    if (data.password) {
      // Only validate password strength for registration
      // For login, just check it's not empty
      if (formType === 'register') {
        const passwordValidation = validatePassword(data.password);
        if (!passwordValidation.valid) {
          errors.password = passwordValidation.errors.join(', ');
        } else {
          // Don't sanitize password - use as-is
          sanitized.password = data.password;
        }
      } else {
        // Login: accept any password, server will verify
        sanitized.password = data.password;
      }
    } else {
      errors.password = 'Contraseña es requerida';
    }
  }

  // Name validation (required for register)
  if (formType === 'register') {
    if (data.name) {
      const sanitizedName = sanitizeName(data.name);
      if (sanitizedName.length < 2) {
        errors.name = 'Nombre debe tener al menos 2 caracteres';
      } else if (sanitizedName.length > 100) {
        errors.name = 'Nombre demasiado largo';
      } else {
        sanitized.name = sanitizedName;
      }
    } else {
      errors.name = 'Nombre es requerido';
    }

    // Confirm password validation
    if (data.confirmPassword) {
      if (data.password !== data.confirmPassword) {
        errors.confirmPassword = 'Las contraseñas no coinciden';
      } else {
        sanitized.confirmPassword = data.confirmPassword;
      }
    } else {
      errors.confirmPassword = 'Confirmar contraseña es requerido';
    }
  }

  return {
    valid: Object.keys(errors).length === 0,
    errors,
    sanitized
  };
}

/**
 * Checks for common weak passwords
 */
const COMMON_PASSWORDS = [
  '12345678', 'password', 'qwerty123', 'abc12345',
  'password123', '12345678', 'iloveyou', 'admin123'
];

export function isCommonPassword(password: string): boolean {
  const lower = password.toLowerCase();
  return COMMON_PASSWORDS.some(common => lower.includes(common));
}

/**
 * Rate limiting helper (client-side check)
 */
export class ClientRateLimiter {
  private attempts: Map<string, number[]> = new Map();

  canAttempt(key: string, maxAttempts: number = 5, windowMs: number = 60000): boolean {
    const now = Date.now();
    const attempts = this.attempts.get(key) || [];

    // Remove old attempts outside the window
    const recentAttempts = attempts.filter(time => now - time < windowMs);

    // Check if limit exceeded
    if (recentAttempts.length >= maxAttempts) {
      return false;
    }

    // Add current attempt
    recentAttempts.push(now);
    this.attempts.set(key, recentAttempts);

    return true;
  }

  getRemainingAttempts(key: string, maxAttempts: number = 5, windowMs: number = 60000): number {
    const now = Date.now();
    const attempts = this.attempts.get(key) || [];
    const recentAttempts = attempts.filter(time => now - time < windowMs);
    return Math.max(0, maxAttempts - recentAttempts.length);
  }

  getTimeUntilReset(key: string, windowMs: number = 60000): number {
    const attempts = this.attempts.get(key) || [];
    if (attempts.length === 0) return 0;

    const oldestAttempt = Math.min(...attempts);
    const timeUntilReset = windowMs - (Date.now() - oldestAttempt);

    return Math.max(0, timeUntilReset);
  }

  reset(key: string): void {
    this.attempts.delete(key);
  }
}

// Export singleton instance
export const rateLimiter = new ClientRateLimiter();
`;

  // ============================================
  // SERVICE FILES - Required by PublicAuthForms
  // ============================================

  // src/services/rolesService.ts
  files['src/services/rolesService.ts'] = `${deployTimestamp}import { supabase } from '../lib/supabase';

export const rolesService = {
  async getRolesByApplication(internalAppId: string) {
    try {
      const { data, error } = await supabase
        .from('application_roles')
        .select('*')
        .eq('application_id', internalAppId)
        .order('display_name');

      if (error) {
        console.error('Error fetching roles from DB:', error);
        throw error;
      }

      console.log('✅ Roles loaded:', data);
      return data || [];
    } catch (error) {
      console.error('❌ Error fetching roles:', error);
      return [];
    }
  },

  async getAvailableRolesForRegistration(internalAppId: string) {
    try {
      // Try with both columns first
      let { data, error } = await supabase
        .from('application_roles')
        .select('*')
        .eq('application_id', internalAppId)
        .order('display_name');

      // If columns exist, filter in JS (safer than SQL)
      if (data) {
        // Filter by available_for_registration if it exists
        const filtered = data.filter(role => {
          // If column doesn't exist, show all roles
          if (role.hasOwnProperty('available_for_registration')) {
            return role.available_for_registration === true;
          }
          // If column doesn't exist, show all non-admin roles or default roles
          return role.is_default === true || role.name !== 'admin';
        });

        console.log('✅ Roles for registration loaded:', filtered);
        return filtered || [];
      }

      if (error) {
        console.error('Error fetching roles for registration:', error);
        return [];
      }

      return [];
    } catch (error) {
      console.error('❌ Error fetching roles for registration:', error);
      return [];
    }
  }
};
`;

  // src/services/applicationService.ts
  files['src/services/applicationService.ts'] = `${deployTimestamp}import { supabase } from '../lib/supabase';

export const applicationService = {
  async getApplicationByApplicationId(applicationId: string) {
    try {
      const { data, error } = await supabase
        .from('applications')
        .select('*')
        .eq('application_id', applicationId)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error fetching application:', error);
      return null;
    }
  },

  async verifyApiKey(appId: string, apiKey: string) {
    try {
      const { data, error } = await supabase
        .from('api_keys')
        .select('*')
        .eq('application_id', appId)
        .eq('key', apiKey)
        .eq('is_active', true)
        .maybeSingle();

      if (error) throw error;
      return !!data;
    } catch (error) {
      console.error('Error verifying API key:', error);
      return false;
    }
  },

  async getBranding(internalAppId: string) {
    try {
      const { data, error } = await supabase
        .from('branding_configs')
        .select('*')
        .eq('application_id', internalAppId)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error fetching branding:', error);
      return null;
    }
  },

  async getBrandingByApplicationId(internalAppId: string) {
    try {
      const { data, error } = await supabase
        .from('branding_configs')
        .select('*')
        .eq('application_id', internalAppId)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error fetching branding:', error);
      return null;
    }
  }
};
`;

  // src/services/ipService.ts
  files['src/services/ipService.ts'] = `${deployTimestamp}export const ipService = {
  async getClientIP() {
    try {
      const ipResponse = await fetch('https://api.ipify.org?format=json');
      const { ip } = await ipResponse.json();
      console.log('Detected client IP:', ip);
      return ip;
    } catch (error) {
      console.error('Error getting client IP:', error);
      return '0.0.0.0';
    }
  }
};
`;

  files['src/services/envConfigService.ts'] = `${deployTimestamp}declare global {
  interface Window {
    __ENV__?: Record<string, string>;
  }
}

const DEFAULT_ENV_CONFIG_URL = 'https://ffihaeatoundrjzgtpzk.supabase.co/functions/v1/get-env';
const DEFAULT_ENV_CONFIG_ACCESS_KEY = '4a63305a316f04fe2acf33b2b63135925bd3a0523c1fd453a42fbf1fc49e6240';
const DEFAULT_SUPABASE_URL = 'https://sfqtmnncgiqkveaoqckt.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcXRtbm5jZ2lxa3ZlYW9xY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDEyNDMsImV4cCI6MjA3NTM3NzI0M30.n2yaYrfHDLAFePP1tA3-250P6bgKmf696fYJFHfRZaQ';

class EnvConfigService {
  private loaded = false;
  private loadPromise: Promise<void> | null = null;

  async loadConfig(): Promise<void> {
    if (this.loaded) return;
    if (this.loadPromise) return this.loadPromise;

    this.loadPromise = this.fetchConfig().finally(() => {
      this.loadPromise = null;
    });

    return this.loadPromise;
  }

  private getFallbackVariables(): Record<string, string> {
    return {
      VITE_SUPABASE_URL: (import.meta.env.VITE_SUPABASE_URL as string | undefined) || DEFAULT_SUPABASE_URL,
      VITE_SUPABASE_ANON_KEY: (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) || DEFAULT_SUPABASE_ANON_KEY,
      ...(window.__ENV__ || {})
    };
  }

  private applyVariables(variables: Record<string, string>) {
    window.__ENV__ = {
      ...this.getFallbackVariables(),
      ...variables
    };
    this.loaded = true;
  }

  private async fetchConfig(): Promise<void> {
    const configuredUrl = (import.meta.env.VITE_ENV_CONFIG_URL as string | undefined)?.trim();
    const configuredAccessKey = (import.meta.env.VITE_ENV_CONFIG_ACCESS_KEY as string | undefined)?.trim()
      || DEFAULT_ENV_CONFIG_ACCESS_KEY;

    const candidates = [
      '/get-env',
      configuredUrl,
      DEFAULT_ENV_CONFIG_URL
    ].filter((value, index, array): value is string => !!value && array.indexOf(value) === index);

    for (const url of candidates) {
      try {
        const response = await fetch(url, {
          method: 'GET',
          headers: configuredAccessKey
            ? {
                'X-Access-Key': configuredAccessKey,
                'Content-Type': 'application/json'
              }
            : {
                'Content-Type': 'application/json'
              }
        });

        if (!response.ok) {
          throw new Error('Config response ' + response.status);
        }

        const payload = await response.json();
        const variables = payload?.variables && typeof payload.variables === 'object'
          ? payload.variables
          : payload;

        if (!variables || typeof variables !== 'object' || !Object.keys(variables).length) {
          throw new Error('No variables returned by ' + url);
        }

        this.applyVariables(variables as Record<string, string>);
        return;
      } catch (error) {
        console.warn('No se pudo cargar configuración desde', url, error);
      }
    }

    this.applyVariables({});
  }

  getVariable(key: string): string {
    return (window.__ENV__?.[key] || (import.meta.env[key] as string | undefined) || '').trim();
  }
}

export const envConfigService = new EnvConfigService();

export function getEnvVariable(key: string): string {
  return envConfigService.getVariable(key);
}
`;

  files['src/lib/supabaseRuntime.ts'] = `${deployTimestamp}import { getEnvVariable } from '../services/envConfigService';

function resolveEnvValue(key: string): string {
  return (getEnvVariable(key) || (import.meta.env[key] as string | undefined) || '').trim();
}

export function getSupabaseUrl(): string {
  return resolveEnvValue('VITE_SUPABASE_URL').replace(/\\/+$/, '');
}

export function getSupabaseAnonKey(): string {
  return resolveEnvValue('VITE_SUPABASE_ANON_KEY');
}

export function requireSupabaseUrl(): string {
  const value = getSupabaseUrl();
  if (!value || !/^https?:\\/\\//i.test(value)) {
    throw new Error('VITE_SUPABASE_URL no está configurada correctamente');
  }
  return value;
}

export function requireSupabaseAnonKey(): string {
  const value = getSupabaseAnonKey();
  if (!value) {
    throw new Error('VITE_SUPABASE_ANON_KEY no está configurada correctamente');
  }
  return value;
}
`;

  // src/lib/config.ts - Configuration for public auth forms
  // This file is auto-generated with the application's API credentials
  files['src/lib/config.ts'] = `${deployTimestamp}// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: '${applicationId}',
  apiKey: '${apiKey}'
};
`;

  // src/lib/supabase.ts - Supabase client for loading branding data
  files['src/lib/supabase.ts'] = `${deployTimestamp}import { createClient } from '@supabase/supabase-js';
import { requireSupabaseAnonKey, requireSupabaseUrl } from './supabaseRuntime';

export const supabase = createClient(requireSupabaseUrl(), requireSupabaseAnonKey());
`;

  // netlify.toml for deployment configuration
  files['netlify.toml'] = `[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;

  // _redirects file (backup for netlify.toml)
  files['_redirects'] = `/*    /index.html   200`;

  // .gitignore - IMPORTANT: Only ignore build outputs, keep all source files
  files['.gitignore'] = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Production build
dist/
build/

# Misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Editor directories and files
.vscode/
.idea/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Temporary files
*.tmp
*.temp
.cache/
`;

  // README.md
  files['README.md'] = `# AuthSystem Public Forms

Este es un proyecto standalone de formularios públicos para AuthSystem.

## Deployment

Este proyecto está configurado para deployarse automáticamente en Netlify.

## Configuración

La configuración de la aplicación está embebida en el archivo \`src/lib/config.ts\`:

- apiBaseUrl: URL de la API pública de AuthSystem
- appId: ID de la aplicación
- apiKey: API key de la aplicación

## Rutas

- \`/login\` - Formulario de inicio de sesión
- \`/register\` - Formulario de registro
- \`/reset-password\` - Formulario de recuperación de contraseña

Todas las rutas requieren los parámetros \`app_id\` y \`api_key\` en la URL.
`;

  // ============================================
  // ALL FILES READY - Complete React application
  // ============================================
  console.log(`✅ Generated ${Object.keys(files).length} files for complete React app`);
  console.log(`   - React components with branding support`);
  console.log(`   - Service layer for API calls`);
  console.log(`   - Supabase client configuration`);
  console.log(`   - TypeScript configuration`);
  console.log(`   - Vite build configuration`);
  console.log(`   - Netlify deployment configuration`);

  return files;
}
