/**
 * React Project Helper
 *
 * Instead of generating static HTML files, this helper prepares
 * configuration files that will be added to the GitHub repository.
 *
 * The actual React source code is already in the repo, so we only
 * need to add/update configuration files with app-specific settings.
 */

/**
 * Get configuration files to add to the React project in GitHub
 * These files will configure the app for a specific application
 */
export async function getReactConfigFiles(
  applicationId: string,
  apiKey: string,
  supabaseUrl: string,
  supabaseAnonKey: string,
  branding?: any
): Promise<Record<string, string>> {
  const files: Record<string, string> = {};

  // .env.production - App-specific environment variables
  files['.env.production'] = `# Auto-generated configuration for Application: ${applicationId}
# Generated: ${new Date().toISOString()}

# Supabase Configuration
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseAnonKey}

# Application Configuration
VITE_DEFAULT_APP_ID=${applicationId}
VITE_DEFAULT_API_KEY=${apiKey}

# Build Configuration
NODE_ENV=production
`;

  // netlify.toml - Netlify build configuration
  files['netlify.toml'] = `# Netlify Configuration
# Auto-generated for Application: ${applicationId}

[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "${supabaseUrl}"
  VITE_SUPABASE_ANON_KEY = "${supabaseAnonKey}"
  VITE_DEFAULT_APP_ID = "${applicationId}"
  VITE_DEFAULT_API_KEY = "${apiKey}"

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
`;

  // _redirects - Backup for SPA routing
  files['_redirects'] = `# SPA Routing
/*    /index.html   200
`;

  // README with deployment info
  files['DEPLOYMENT.md'] = `# Deployment Configuration

**Application ID**: ${applicationId}
**Deployed**: ${new Date().toISOString()}
**Supabase Project**: ${supabaseUrl}

## URLs

Access the authentication forms at:

- **Login**: \`/login?app_id=${applicationId}&api_key=${apiKey.substring(0, 20)}...&redirect_uri=YOUR_CALLBACK\`
- **Register**: \`/register?app_id=${applicationId}&api_key=${apiKey.substring(0, 20)}...&redirect_uri=YOUR_CALLBACK\`
- **Reset Password**: \`/reset-password?app_id=${applicationId}&api_key=${apiKey.substring(0, 20)}...&redirect_uri=YOUR_CALLBACK\`

## Features

This deployment includes the complete React application with:

✅ **Full React Components**
- PublicAuthForms component with all validations
- Dynamic role loading from database
- Password confirmation field
- Custom branding support

✅ **Authentication Features**
- Email/Password login
- User registration with roles
- Password reset
- IP blocking
- Custom branding per application

✅ **Form Validation**
- Email format validation
- Password strength requirements
- Password confirmation matching
- Required field validation
- Role selection

## Environment Variables

The following environment variables are configured:

\`\`\`
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseAnonKey.substring(0, 20)}...
VITE_DEFAULT_APP_ID=${applicationId}
VITE_DEFAULT_API_KEY=${apiKey.substring(0, 20)}...
\`\`\`

## Build Process

Netlify will automatically:
1. Clone the repository
2. Run \`npm install\`
3. Run \`npm run build\`
4. Deploy the \`dist/\` folder
5. Configure SPA routing for React Router

## Auto-Deploy

This site is configured for continuous deployment:
- Every push to the repository triggers a new build
- Netlify monitors the GitHub repository
- Changes are deployed automatically

---

*This configuration was automatically generated by AuthSystem*
`;

  return files;
}

/**
 * Check if the repository already has the React source code
 * If not, we need to initialize it first
 */
export function validateReactProject(): {
  isValid: boolean;
  missingFiles: string[];
  instructions: string;
} {
  // List of critical files that must exist in the repo
  const requiredFiles = [
    'package.json',
    'src/App.tsx',
    'src/main.tsx',
    'src/components/auth/PublicAuthForms.tsx',
    'vite.config.ts',
    'index.html'
  ];

  // In a real implementation, we would check if these files exist in the repo
  // For now, we'll assume they exist

  return {
    isValid: true,
    missingFiles: [],
    instructions: 'Repository is ready for deployment'
  };
}

/**
 * Get the message to display when committing config changes
 */
export function getCommitMessage(applicationId: string, environmentName: string): string {
  return `Configure deployment for ${environmentName}

Application ID: ${applicationId}
Timestamp: ${new Date().toISOString()}

This commit updates the production configuration files:
- .env.production
- netlify.toml
- _redirects
- DEPLOYMENT.md

These changes configure the React app for this specific application.
The full React source code is already in the repository.

Auto-generated by AuthSystem`;
}
