import { ThemePreset, BrandingConfig } from '../types';

export const themePresets: ThemePreset[] = [
  {
    name: 'modern-glass',
    label: 'Modern Glass',
    description: 'Glassmorphism effect with blur and transparencies',
    config: {
      theme_style: 'modern-glass',
      primary_color: '#3B82F6',
      secondary_color: '#8B5CF6',
      accent_color: '#EC4899',
      background_color: '#FFFFFF',
      text_color: '#FFFFFF',
      gradient_start: '#3B82F6',
      gradient_end: '#EC4899',
      error_color: '#EF4444',
      success_color: '#10B981',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'glass',
      card_background: 'rgba(255, 255, 255, 0.1)',
      card_blur: 20,
      input_style: 'outlined',
      input_background: 'rgba(255, 255, 255, 0.1)',
      input_border_color: 'rgba(255, 255, 255, 0.2)',
      input_focus_color: 'rgba(255, 255, 255, 0.4)',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: true,
      border_radius: 16,
      shadow_intensity: 'strong',
      use_gradient: true,
      glass_effect: true,
      blur_background: true,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please try again or reset your password',
      redirect_delay: 2000,
      message_loading_bg: 'rgba(59, 130, 246, 0.2)',
      message_success_bg: 'rgba(16, 185, 129, 0.2)',
      message_error_bg: 'rgba(239, 68, 68, 0.2)'
    }
  },
  {
    name: 'minimal-clean',
    label: 'Minimal Clean',
    description: 'Minimalist design with clean lines',
    config: {
      theme_style: 'minimal-clean',
      primary_color: '#1F2937',
      secondary_color: '#6B7280',
      accent_color: '#1F2937',
      background_color: '#F9FAFB',
      text_color: '#1F2937',
      error_color: '#DC2626',
      success_color: '#059669',
      warning_color: '#D97706',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'flat',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'underlined',
      input_background: 'transparent',
      input_border_color: '#D1D5DB',
      input_focus_color: '#1F2937',
      button_style: 'square',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: false,
      border_radius: 0,
      shadow_intensity: 'none',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'relaxed',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Double-check your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#DBEAFE',
      message_success_bg: '#D1FAE5',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'corporate',
    label: 'Corporate Professional',
    description: 'Professional corporate style with pronounced shadows',
    config: {
      theme_style: 'corporate',
      primary_color: '#2563EB',
      secondary_color: '#1E40AF',
      accent_color: '#3B82F6',
      background_color: '#F1F5F9',
      text_color: '#1E293B',
      error_color: '#DC2626',
      success_color: '#16A34A',
      warning_color: '#EA580C',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'filled',
      input_background: '#F8FAFC',
      input_border_color: 'transparent',
      input_focus_color: '#2563EB',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: false,
      border_radius: 12,
      shadow_intensity: 'strong',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#DBEAFE',
      message_success_bg: '#DCFCE7',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'gradient-bold',
    label: 'Gradient Bold',
    description: 'Vibrant gradients with modern effects',
    config: {
      theme_style: 'gradient-bold',
      primary_color: '#06B6D4',
      secondary_color: '#3B82F6',
      accent_color: '#8B5CF6',
      background_color: '#0F172A',
      text_color: '#FFFFFF',
      gradient_start: '#06B6D4',
      gradient_end: '#8B5CF6',
      error_color: '#EF4444',
      success_color: '#10B981',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'glass',
      card_background: 'rgba(15, 23, 42, 0.5)',
      card_blur: 20,
      input_style: 'outlined',
      input_background: 'rgba(15, 23, 42, 0.5)',
      input_border_color: '#334155',
      input_focus_color: '#06B6D4',
      button_style: 'rounded',
      button_variant: 'gradient',
      button_size: 'medium',
      button_hover_transform: true,
      border_radius: 16,
      shadow_intensity: 'strong',
      use_gradient: true,
      glass_effect: true,
      blur_background: true,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Verify your information and try again',
      redirect_delay: 2000,
      message_loading_bg: 'linear-gradient(to right, rgba(6, 182, 212, 0.2), rgba(59, 130, 246, 0.2))',
      message_success_bg: 'linear-gradient(to right, rgba(16, 185, 129, 0.2), rgba(5, 150, 105, 0.2))',
      message_error_bg: 'linear-gradient(to right, rgba(239, 68, 68, 0.2), rgba(249, 115, 22, 0.2))'
    }
  },
  {
    name: 'neumorphic',
    label: 'Neumorphic Soft',
    description: 'Soft UI with subtle shadows',
    config: {
      theme_style: 'neumorphic',
      primary_color: '#3B82F6',
      secondary_color: '#60A5FA',
      accent_color: '#2563EB',
      background_color: '#E5E7EB',
      text_color: '#1F2937',
      error_color: '#EF4444',
      success_color: '#10B981',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'neumorphic',
      card_background: 'linear-gradient(145deg, #E5E7EB, #D1D5DB)',
      card_blur: 0,
      input_style: 'filled',
      input_background: 'linear-gradient(145deg, #E5E7EB, #D1D5DB)',
      input_border_color: 'transparent',
      input_focus_color: '#3B82F6',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: true,
      border_radius: 16,
      shadow_intensity: 'medium',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please check your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#DBEAFE',
      message_success_bg: '#D1FAE5',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'dark-elegant',
    label: 'Dark Elegant',
    description: 'Sophisticated dark theme with gold accents',
    config: {
      theme_style: 'dark-elegant',
      primary_color: '#D4AF37',
      secondary_color: '#9C7B16',
      accent_color: '#FFD700',
      background_color: '#0F0F0F',
      text_color: '#F5F5F5',
      error_color: '#EF4444',
      success_color: '#10B981',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#1A1A1A',
      card_blur: 0,
      input_style: 'outlined',
      input_background: '#0F0F0F',
      input_border_color: '#333333',
      input_focus_color: '#D4AF37',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: true,
      border_radius: 8,
      shadow_intensity: 'strong',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: 'rgba(212, 175, 55, 0.2)',
      message_success_bg: 'rgba(16, 185, 129, 0.2)',
      message_error_bg: 'rgba(239, 68, 68, 0.2)'
    }
  },
  {
    name: 'ocean-blue',
    label: 'Ocean Blue',
    description: 'Calming ocean-inspired blue tones',
    config: {
      theme_style: 'ocean-blue',
      primary_color: '#0EA5E9',
      secondary_color: '#0284C7',
      accent_color: '#06B6D4',
      background_color: '#F0F9FF',
      text_color: '#0C4A6E',
      error_color: '#DC2626',
      success_color: '#059669',
      warning_color: '#D97706',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'filled',
      input_background: '#E0F2FE',
      input_border_color: 'transparent',
      input_focus_color: '#0EA5E9',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: false,
      border_radius: 12,
      shadow_intensity: 'medium',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please check your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#DBEAFE',
      message_success_bg: '#D1FAE5',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'sunset-warm',
    label: 'Sunset Warm',
    description: 'Warm sunset colors with orange and pink',
    config: {
      theme_style: 'sunset-warm',
      primary_color: '#F97316',
      secondary_color: '#EA580C',
      accent_color: '#FB923C',
      background_color: '#FFF7ED',
      text_color: '#7C2D12',
      gradient_start: '#F97316',
      gradient_end: '#EC4899',
      error_color: '#DC2626',
      success_color: '#16A34A',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'outlined',
      input_background: '#FFFFFF',
      input_border_color: '#FDBA74',
      input_focus_color: '#F97316',
      button_style: 'rounded',
      button_variant: 'gradient',
      button_size: 'medium',
      button_hover_transform: true,
      border_radius: 12,
      shadow_intensity: 'medium',
      use_gradient: true,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your information and try again',
      redirect_delay: 2000,
      message_loading_bg: '#FFEDD5',
      message_success_bg: '#DCFCE7',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'forest-green',
    label: 'Forest Green',
    description: 'Natural green tones inspired by nature',
    config: {
      theme_style: 'forest-green',
      primary_color: '#059669',
      secondary_color: '#047857',
      accent_color: '#10B981',
      background_color: '#F0FDF4',
      text_color: '#064E3B',
      error_color: '#DC2626',
      success_color: '#16A34A',
      warning_color: '#D97706',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'filled',
      input_background: '#DCFCE7',
      input_border_color: 'transparent',
      input_focus_color: '#059669',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: false,
      border_radius: 10,
      shadow_intensity: 'medium',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please check your email and password',
      redirect_delay: 2000,
      message_loading_bg: '#D1FAE5',
      message_success_bg: '#A7F3D0',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'royal-purple',
    label: 'Royal Purple',
    description: 'Elegant purple with luxurious feel',
    config: {
      theme_style: 'royal-purple',
      primary_color: '#7C3AED',
      secondary_color: '#6D28D9',
      accent_color: '#8B5CF6',
      background_color: '#FAF5FF',
      text_color: '#4C1D95',
      error_color: '#DC2626',
      success_color: '#10B981',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'outlined',
      input_background: '#FFFFFF',
      input_border_color: '#C4B5FD',
      input_focus_color: '#7C3AED',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: true,
      border_radius: 12,
      shadow_intensity: 'strong',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#EDE9FE',
      message_success_bg: '#D1FAE5',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'arctic-light',
    label: 'Arctic Light',
    description: 'Cool light palette with clean cyan highlights',
    config: {
      theme_style: 'custom',
      primary_color: '#0EA5E9',
      secondary_color: '#0284C7',
      accent_color: '#22D3EE',
      background_color: '#F8FAFC',
      text_color: '#0F172A',
      error_color: '#DC2626',
      success_color: '#16A34A',
      warning_color: '#D97706',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      input_style: 'outlined',
      input_background: '#FFFFFF',
      input_border_color: '#CBD5E1',
      input_focus_color: '#0EA5E9',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      border_radius: 12,
      shadow_intensity: 'light',
      use_gradient: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#DBEAFE',
      message_success_bg: '#DCFCE7',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'midnight-neon',
    label: 'Midnight Neon',
    description: 'Dark futuristic style with neon accents',
    config: {
      theme_style: 'custom',
      primary_color: '#22D3EE',
      secondary_color: '#818CF8',
      accent_color: '#A78BFA',
      background_color: '#020617',
      text_color: '#E2E8F0',
      gradient_start: '#22D3EE',
      gradient_end: '#818CF8',
      error_color: '#EF4444',
      success_color: '#10B981',
      warning_color: '#F59E0B',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'glass',
      card_background: 'rgba(15, 23, 42, 0.7)',
      card_blur: 16,
      input_style: 'filled',
      input_background: 'rgba(30, 41, 59, 0.9)',
      input_border_color: '#334155',
      input_focus_color: '#22D3EE',
      button_style: 'rounded',
      button_variant: 'gradient',
      button_size: 'medium',
      border_radius: 14,
      shadow_intensity: 'strong',
      use_gradient: true,
      glass_effect: true,
      blur_background: true,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: 'rgba(34, 211, 238, 0.2)',
      message_success_bg: 'rgba(16, 185, 129, 0.2)',
      message_error_bg: 'rgba(239, 68, 68, 0.2)'
    }
  },
  {
    name: 'sandstone-warm',
    label: 'Sandstone Warm',
    description: 'Warm earthy tones with soft contrast',
    config: {
      theme_style: 'custom',
      primary_color: '#B45309',
      secondary_color: '#92400E',
      accent_color: '#F59E0B',
      background_color: '#FFFBEB',
      text_color: '#78350F',
      error_color: '#DC2626',
      success_color: '#15803D',
      warning_color: '#D97706',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'elevated',
      card_background: '#FFFFFF',
      input_style: 'filled',
      input_background: '#FEF3C7',
      input_border_color: '#FDE68A',
      input_focus_color: '#B45309',
      button_style: 'rounded',
      button_variant: 'solid',
      button_size: 'medium',
      border_radius: 10,
      shadow_intensity: 'medium',
      use_gradient: false,
      blur_background: false,
      enable_animations: true,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please verify your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#FEF3C7',
      message_success_bg: '#DCFCE7',
      message_error_bg: '#FEE2E2'
    }
  },
  {
    name: 'monochrome',
    label: 'Monochrome',
    description: 'Classic black and white minimalist design',
    config: {
      theme_style: 'monochrome',
      primary_color: '#000000',
      secondary_color: '#404040',
      accent_color: '#1A1A1A',
      background_color: '#FFFFFF',
      text_color: '#000000',
      error_color: '#DC2626',
      success_color: '#16A34A',
      warning_color: '#D97706',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      font_size_scale: 'medium',
      card_style: 'flat',
      card_background: '#FFFFFF',
      card_blur: 0,
      input_style: 'outlined',
      input_background: '#FFFFFF',
      input_border_color: '#E5E5E5',
      input_focus_color: '#000000',
      button_style: 'square',
      button_variant: 'solid',
      button_size: 'medium',
      button_hover_transform: false,
      border_radius: 4,
      shadow_intensity: 'none',
      use_gradient: false,
      glass_effect: false,
      blur_background: false,
      enable_animations: false,
      animation_speed: 'normal',
      form_width: 'medium',
      spacing: 'normal',
      message_loading_text: 'Authenticating...',
      message_success_text: 'Welcome back! Redirecting to your dashboard...',
      message_error_text: 'Invalid credentials. Please check your email and password.',
      message_error_help_text: 'Please check your credentials and try again',
      redirect_delay: 2000,
      message_loading_bg: '#F5F5F5',
      message_success_bg: '#DCFCE7',
      message_error_bg: '#FEE2E2'
    }
  }
];

export function getThemePreset(name: string): ThemePreset | undefined {
  return themePresets.find(theme => theme.name === name);
}

export function applyThemePreset(name: string, currentConfig: Partial<BrandingConfig>): BrandingConfig {
  const preset = getThemePreset(name);
  if (!preset) {
    return currentConfig as BrandingConfig;
  }

  return {
    ...currentConfig,
    ...preset.config
  } as BrandingConfig;
}

export function getDefaultBrandingConfig(): BrandingConfig {
  return {
    theme_style: 'corporate',
    primary_color: '#2563EB',
    secondary_color: '#1E40AF',
    accent_color: '#3B82F6',
    background_color: '#F1F5F9',
    text_color: '#1E293B',
    error_color: '#DC2626',
    success_color: '#16A34A',
    warning_color: '#EA580C',
    font_family: 'Inter',
    heading_font_family: 'Inter',
    font_size_scale: 'medium',
    card_style: 'elevated',
    card_background: '#FFFFFF',
    card_blur: 0,
    input_style: 'filled',
    input_background: '#F8FAFC',
    input_border_color: 'transparent',
    input_focus_color: '#2563EB',
    button_style: 'rounded',
    button_variant: 'solid',
    button_size: 'medium',
    button_hover_transform: false,
    border_radius: 12,
    shadow_intensity: 'medium',
    use_gradient: false,
    glass_effect: false,
    blur_background: false,
    enable_animations: true,
    animation_speed: 'normal',
    form_width: 'medium',
    spacing: 'normal',
    message_loading_text: 'Authenticating...',
    message_success_text: 'Welcome back! Redirecting to your dashboard...',
    message_error_text: 'Invalid credentials. Please check your email and password.',
    message_error_help_text: 'Please verify your credentials and try again',
    redirect_delay: 2000,
    message_loading_bg: '#DBEAFE',
    message_success_bg: '#DCFCE7',
    message_error_bg: '#FEE2E2'
  };
}
